### ISSUE TITLE
errors after upgrading from 1.3.8

### ISSUE THREAD

**Issue by FerdinandGold** [phaag/nfsen#11]
I tried upgrading our nfsen 1.3.8 running on FreeBSD 13.2 today. The upgrade script ran fine. However I'm now seeing errors in the Apache log:

`[Mon May 08 14:47:47.598817 2023] [php:error] [pid 33246] [client x.x.x.x:47346] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: int + string in /usr/local/www/nfsen/details.php:1153\nStack trace:\n#0 /usr/local/www/nfsen/nfsen.php(778): DisplayDetails()\n#1 {main}\n  thrown in /usr/local/www/nfsen/details.php on line 1153, referer: https://xxxx/index.php?tab=1
[Mon May 08 14:47:47.599014 2023] [php:error] [pid 33246] [client x.x.x.x:47346] PHP Fatal error:  Uncaught Exception: Serialization of 'Socket' is not allowed in [no active file]:0\nStack trace:\n#0 {main}\n  thrown in [no active file] on line 0, referer: https://xxxx/index.php?tab=1
`

Certain profiles don't seem to work (correctly). Any ideas?

**Comment by phaag** [comment]
I guess php could be too new. Can you try with an old version?

**Comment by dgeo** [comment]
Running here (with last patches) with php 8.1.17

**Comment by FerdinandGold** [comment]
Running 8.1.17 here as well, so the PHP version should not be the issue. My colleague fixed the problem for now by creating a shadow profile. This way all data is shown and the PHP errors are gone... seems to have mitigated the issue for now - but I have no idea how. 😁
Once we get new hardware in a couple of months we will setup things from scratch. 

Thanks for answering!

**Comment by dgeo** [comment]
we only use live and shadow profiles here, I didn't test other profiles...

**Comment by phaag** [comment]
Added string to int for php 8.x in main repo.
There may be other places where interval() would be required.
