### ISSUE TITLE
ERROR: Illegal value 'xxx' for 'DefaultFilter'!

### ISSUE THREAD

**Issue by tfmotu** [phaag/nfsen#18]
Hi, firstly thanks for the work done with nfsen.
I want to share with you an issue that I have.
If I create a filter and I try to use it an error is shown. For example, I create a filter named TCP:
"ERROR: Illegal value 'TCP' for 'DefaultFilter'!"
I have used other filter names, for example using numbers, but with no luck. 
nfsen is installed on debian 12, PHP 8.2.7 with: 
--enable-nfprofile --enable-sflow --enable-nfpcapd --enable-maxmind -enable-nsel --enable-nftrack --enable-readpcap

Thanks in advance.

**Comment by gondimcodes** [comment]
@tfmotu Are you able to create new profiles in nfsen? If yes, could you tell me if you are using the Debian 12 nfdump packages or did you use version 1.7.2 from the git here?

**Comment by phaag** [comment]
Can you clear the cookie from the nfsen web page and try again?

**Comment by phaag** [comment]
Fixed for newer php versions. Use main repo.
