### ISSUE TITLE
Adding profile with start in the past: -z=lz4' not a directory

### ISSUE THREAD

**Issue by bernhardschmidt** [phaag/nfsen#20]
Latest master/main of nfdump and nfsen. Adding a profile that starts in the past (analyzing past data) leads to

```
Aug 23 19:48:12 netflow nfsen[740256]: Build Profile 'MGI':         Completed: 52.1%%
Aug 23 19:48:12 netflow nfprofile[740832]: '-z=lz4' not a directory
Aug 23 19:48:12 netflow nfprofile[740833]: '-z=lz4' not a directory
```

Continous profiles work fine, and new data is also added to the created profile. But the historic data is not available.

```
root@netflow:/opt/nfsen/etc# grep ZIP nfsen.conf
$ZIPcollected    = 1;
$ZIPprofiles     = 1;
```

**Comment by phaag** [comment]
This looks like you have an old nfprofile binary. Please recompile the latest nfdump master repo and verify, that you have added ``--enable-nfprofile`` to the configure command

**Comment by phaag** [comment]
Always update nfdump first, before upgrading/installing NfSen!
Any success on this issue?

**Comment by bernhardschmidt** [comment]
Nope, I can still reproduce it.

nfsen 1.3.10 now

```
% nfprofile -V
nfprofile: Version: 1.7.2-release Options: NSEL-NEL Date: Fri Aug 18 22:01:04 2023
```

That nfprofile version is actually a git snapshot of 20230812, this HEAD: https://github.com/phaag/nfdump/commit/696f5632f661c15ae66e34fed5e7e05e75cbce33

**Comment by phaag** [comment]
Fixed in latest main and new release v.1.3.11. Do not use v.1.3.10
