### ISSUE TITLE
The "-z=lz4" argument is not numeric  when start nfsen 1.3.10

### ISSUE THREAD

**Issue by avelok** [phaag/nfsen#22]
hello! installed the latest version of nfdump 
nfdump: Version: 1.7.3-cfaf6ab Parameters: NSEL-NEL Date: 2023-09-02 13:27:28 +0200

and nfsen 
nfsen-1.3.10

when I start nfsen I get
The "-z=lz4" argument is not numeric in the numeric equation (==) on line 236 of /srv/nfsen/libexec/NfConf.pm.
Running nfcapd:(nat9test) Using the uninitialized value of $nfdump_version in the numeric equation (==) on line 88 of /srv/nfsen/libexec/NfSenRC.pm.
Using the uninitialized $nfdump_version value in the numerical equation (==) on line 121 of /srv/nfsen/libexec/NfSenRC.pm.
-l is a deprecated option and may be removed in the future. Please use -w to set the output directory

What is mean it and how to fix it? As i can understand, I will not compress the data?

because if I grep nfcapd I don't see the -z=lz4

/usr/local/bin/nfcapd -D -p 9995 -u www-data -g www-data -B 3000000 -S 2 -P /srv/nfsen/var/run/p9995.pid -y -t 300 -I nat9test -l /srv/nfsen/profiles-data/live/nat9test

also tried in nfsen.conf instead
$ZIPprofiles = "-z=lz4";
write
$zipprofiles = "1";

Starts without error, but grep nfcapd still doesn't have the -z=lz4 paramert

/usr/local/bin/nfcapd -D -p 9995 -u www-data -g www-data -B 3000000 -S 2 -P /srv/nfsen/var/run/p9995.pid -y -t 300 -I nat9test -l /srv/nfsen/profiles-data/live/nat9test

**Comment by phaag** [comment]
The warning `is not numeric in the numeric equation (==) ` is fixed in the main repo. Newer Perl versions are more picky.
The collector compression also get applied correctly now. Upton now, the `-y` in your output was equivalent to `-z=lz4`. Now it is applied accordingly.

**Comment by avelok** [comment]
close,helped
