### ISSUE TITLE
Undefined var $nfdump_version in install.pl

### ISSUE THREAD

**Issue by hentheor** [phaag/nfsen#3]
In master nfsen's install.pl the var $nfdump_version may be undefined. (a fact for nfdump >= 1.7.x)
The relevant regexps in VerifyConfig() need modification.

(Produces warnings in syslog after issuing nfsen status/start ...)

Thank you

**Comment by phaag** [comment]
Tested with nfdump-1.7.x as well as github master and it works. $nfdump_version = 7.
The regex is rather simple.

**Comment by hentheor** [comment]
You are right. 
I'm using nfdump 1.7.1-1~bpo11+1  from bullseye-backports.
They altered the nfdump -V output!
It reads: 
nfdump: Version: NSEL-NEL1.7.1
in comparison with master's:
nfdump: Version: 1.7.1-release NSEL-NEL, Date:...
 
Thanks.

**Comment by KKostikov** [comment]
Hi.
I have same issue with nfdump: Version: NSEL-NEL1.6.23 how do i fix this?
