### ISSUE TITLE
nfsend dies

### ISSUE THREAD

**Issue by adrimt** [phaag/nfsen#30]
Hi,
we have some issues with Alerts.
$perl -v
This is perl 5, version 36, subversion 0 (v5.36.0) built for x86_64-linux-gnu-thread-multi

Feb  5 09:40:19 server nfsen[12400]: PANIC nfsend dies: Can't locate object method "tid" via package "threads" at /usr/lib/x86_64-linux-gnu/perl-base/XSLoader.pm line 112.
Feb  5 09:40:20 server nfsen[12400]: PANIC nfsend dies: Can't locate auto/Net/SSLeay/DTLS1_VERSI.al in @INC (@INC contains: /usr/local/nfsen/libexec /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /usr/share/perl5/IO/Socket/SSL.pm line 3523.
Feb  5 09:40:20 server nfsen[12400]: PANIC nfsend dies: Can't locate auto/Net/SSLeay/DTLS1_2_VER.al in @INC (@INC contains: /usr/local/nfsen/libexec /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /usr/share/perl5/IO/Socket/SSL.pm line 3523.
Feb  5 09:40:20 server nfsen[12400]: PANIC nfsend dies: Can't locate auto/Net/SSLeay/DTLS1_BAD_V.al in @INC (@INC contains: /usr/local/nfsen/libexec /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.36.0 /usr/local/share/perl/5.36.0 /usr/lib/x86_64-linux-gnu/perl5/5.36 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl-base /usr/lib/x86_64-linux-gnu/perl/5.36 /usr/share/perl/5.36 /usr/local/lib/site_perl) at /usr/share/perl5/IO/Socket/SSL.pm line 3523.
Feb  5 09:40:20 server nfsen[12400]: PANIC nfsend dies: Your vendor has not defined SSLeay macro SSL2_MT_ERROR at /usr/share/perl5/IO/Socket/SSL.pm line 3523.
Feb  5 09:40:20 server nfsen[12400]: PANIC nfsend dies: Your vendor has not defined SSLeay macro SSL2_MT_CLIENT_MASTER_KEY at /usr/share/perl5/IO/Socket/SSL.pm line 3523.
Feb  5 09:40:20 server nfsen[12400]: PANIC nfsend dies: Your vendor has not defined SSLeay macro SSL2_MT_CLIENT_FINISHED at /usr/share/perl5/IO/Socket/SSL.pm line 3523.
Feb  5 09:40:20 server nfsen[12400]: PANIC nfsend dies: Your vendor has not defined SSLeay macro SSL2_MT_SERVER_HELLO at /usr/share/perl5/IO/Socket/SSL.pm line 3523.
Feb  5 09:40:20 server nfsen[12400]: PANIC nfsend dies: Your vendor has not defined SSLeay macro SSL2_MT_SERVER_VERIFY at /usr/share/perl5/IO/Socket/SSL.pm line 3523.
Feb  5 09:40:20 server nfsen[12400]: PANIC nfsend dies: Your vendor has not defined SSLeay macro SSL2_MT_SERVER_FINISHED at /usr/share/perl5/IO/Socket/SSL.pm line 3523.
Feb  5 09:40:20 server nfsen[12400]: PANIC nfsend dies: Your vendor has not defined SSLeay macro SSL2_MT_REQUEST_CERTIFICATE at /usr/share/perl5/IO/Socket/SSL.pm line 3523.
Feb  5 09:40:20 server nfsen[12400]: PANIC nfsend dies: Your vendor has not defined SSLeay macro SSL2_MT_CLIENT_CERTIFICATE at /usr/share/perl5/IO/Socket/SSL.pm line 3523.

**Comment by phaag** [comment]
Hmm .. this looks like a thread problem in one of the perl module. NfSen does not make use of Perl threads. To me it is a distro problem:

```
 Your vendor has not defined SSLeay macro SSL2_MT_ERROR at /usr/share/perl5/IO/Socket/SSL.pm line 3523.
```

You may try to update your OS or modules. Try to remove and reinstall IO::Socket

**Comment by borjam** [comment]
Try to find a Perl package compiled **without threading support** or compile it yourself.

**Comment by adrimt** [comment]
Ths is hard to do since is a system library and may break something else.

**Comment by phaag** [comment]
You need to contact the corresponding package maintainer. It is a perl issue.

**Comment by borjam** [comment]
> Ths is hard to do since is a system library and may break something else.

You can always compile a custom version installing it on another directory. For example, /usr/local2 instead of /usr/local. It will need several packages installed. but it's not that hard. 

That way you can avoid any side effects on the rest of the system. 

Besides, I've been running a non threaded Perl for years on FreeBSD (just changing the compile options for ports) and none of the ports that depend on it has complained so far. I guess Perl has become a sort of "glue" and not so many people are using it for big stuff.
