### ISSUE TITLE
bi-directional aggregation - guard output

### ISSUE THREAD

**Issue by thezoggy** [phaag/nfsen#34]
With nfsen, doing list flows > bi-directional with outputs other than auto/line/long it fails due to unknown output mode 'bi###' unless its auto/line/long.

![Screen Shot 2024-05-23 at 4 25 09 PM](https://github.com/phaag/nfsen/assets/500882/1baf9fd9-8344-4388-9f63-64fa4f8a6318)

Figure there was no plans to add the other bi-output formats, so perhaps at:
https://github.com/phaag/nfsen/blob/main/html/process.php#L70

Have guard to only do -o bi$format if format matches line/long?
`if ( $is_bidir && (in_array($format, array("line", "long") ) {`

**Comment by phaag** [comment]
Well - `bigline` is not supported, however my recommendation would be to create all output formats of your choice in `ndfump.conf`. The guard may be possible, but at some point we should compile the available output formats from what is available and configured in nfdump.
