### ISSUE TITLE
Every time nfsen is restarted, a massive spike in traffic statistics occurs.

### ISSUE THREAD

**Issue by mkoelewijn** [phaag/nfsen#39]
- NfSen: 1.3.11
- Nfdump: 1.7.4-4f409e9

Our configuration is as follows:

NfSen:
- 6 sources with 1/100 sampling (including 1 source receiving flows from 300+ different devices).

Every time nfsen is restarted, a massive spike in traffic statistics occurs. This is unfortunately messing up the graphs over time. Could this be because of the sampling and any idea how to fix this?

<img width="853" alt="Screenshot 2024-08-23 at 09 56 33" src="https://github.com/user-attachments/assets/59b9ed8d-0278-4a82-aad2-89e19e0cef00">

<img width="988" alt="Screenshot 2024-08-23 at 09 56 44" src="https://github.com/user-attachments/assets/8afcbc11-bb1d-46aa-b691-3839d5fed68c">

**Comment by phaag** [comment]
Hmm .. I could assume, that restarting fills up the socket buffer from the time creating until it is processed first. But this is just guessing. You may experiment to skip the first few packet from the socket read when restarting.
