### ISSUE TITLE
dont work graphics

### ISSUE THREAD

**Issue by Dgraf1201** [phaag/nfsen#4]
I installed nfsen and nfdump, netflow builds but graphs don't work.

![image](https://user-images.githubusercontent.com/97558956/217775130-a47f4c87-27a7-4b02-b2c1-05ad3f47fb10.png)
![image](https://user-images.githubusercontent.com/97558956/217775243-c87ed1ad-308d-4b07-95cb-86486833495a.png)

**Comment by phaag** [comment]
Difficult to tell what you are missing. At least some data is visible in the second row. The blue peak is visible. Try to rebuild your profile.

**Comment by sandyWolf** [comment]
nfsen.conf, line 127
switch off $ZIPprofiles (set it to 0)

It tries to open pipe at line 306 in nfsend. Command to be executed looks like this:
`/usr/bin/nfprofile -I -t 1699118700 -p /data/nfsen/profiles-data -P /data/nfsen/profiles-stat -S 1  -y  -L local3 -M /data/nfsen/profiles-data/live/UG:gw -r nfcapd.202311050025`

If you try to run it manualy? you'll get:
`echo '.#VPN_IK#2#to#gw' | /usr/bin/nfprofile -I -t 1699118700 -p /data/nfsen/profiles-data -P /data/nfsen/profiles-stat -S 1  -y  -L local3 -M /data/nfsen/profiles-data/live/UG:gw -r nfcapd.202311050025 
/usr/bin/nfprofile: invalid option -- 'y'
usage /usr/bin/nfprofile [options] 
-h              this text you see right here
-V              Print version and exit.
-D <dns>        Use nameserver <dns> for host lookup.
-M <expr>       Read input from multiple directories.
-r              read input from file
-f              filename with filter syntaxfile
-p              profile data dir.
-P              profile stat dir.
-s              profile subdir.
-Z              Check filter syntax and exit.
-S subdir       Sub directory format. see nfcapd(1) for format
-z              LZO compress flows in output file.
-y              LZ4 compress flows in output file.
-j              BZ2 compress flows in output file.
-t <time>       time for RRD update
`
