### ISSUE TITLE
CYCLETIME not honored when launcing nfcapd processes

### ISSUE THREAD

**Issue by borjam** [phaag/nfsen#5]
Hi,

I´ve updated an old Nfsen installation that was running with CYCLETIME=60. I have noticed that nfcapd is no 
longer launched with -t $CYCLETIME.

Is that deliberate or a bug? I have tried fixing mine by adding the missing bits to NfSenRC.pm and it seems to
work now. Before that nfdump was crashing for every cycle.

```
my $pidfile             = "$NfConf::PIDDIR/p${port}.pid";
my $extensions  = "";
>>>>my $rotate      = join ' ', "-t", $NfConf::CYCLETIME;

```

```
        my $ziparg = $NfConf::ZIPcollected ? '-y' : '';
        my $common_args = "-D -p $port -u $uid -g $gid $buffer_opts $subdirlayout -P $pidfile $ziparg $extensions $rotate";
        my $src_args;

```

**Comment by phaag** [comment]
NfSen apparently did not honour the CYCLETIME when starting the collectors.
But nfdump crashing ?? Maybe it could not find a file, but that's not crashing.

**Comment by borjam** [comment]
It was odd. This is what I saw on the logfile

Feb 10 08:03:24 micro1 nfsen[2859]: Run nfdump failed: Exit: 1, Signal: 0, Coredump: 0 
Feb 10 08:03:24 micro1 nfsen[2859]: Run nfdump failed: Exit: 1, Signal: 0, Coredump: 0 


It was fixed by adding the support for CYCLETIME when starting up nfcapd.

**Comment by phaag** [comment]
So coredump is 0! :) But if you would have selected a start/stop time slot unequal to 300s it does not find that file.

It's fixed in the main branch

**Comment by borjam** [comment]
> On 10 Feb 2023, at 10:26, Peter Haag ***@***.***> wrote:
> 
> 
> So coredump is 0! :) But if you would have selected a start/stop time slot unequal to 300s it does not find that file.
> It's fixed in the main branch

I saw it, thanks!





Borja.
