### ISSUE TITLE
alert - typo for type

### ISSUE THREAD

**Issue by thezoggy** [phaag/nfsen#6]
says packages instead of packets:
https://github.com/phaag/nfsen/blob/1d8fbc3d04680809425fedbc5a30c9c38a919d3a/html/alerting.php#L9

when adding a condition
![Screen Shot 2023-02-20 at 2 48 39 AM](https://user-images.githubusercontent.com/500882/220056962-b9fe9d5b-bdec-4807-b6ce-c5a36c85d3f7.png)

**Comment by phaag** [comment]
Thanks!
